name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install deps
      run: sudo apt install libasound2-dev libudev-dev pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Run interpreter tests
      run: cargo test --lib
    - name: Run interpreter tests (no default)
      run: cargo c --lib --no-default-features
    - name: Run interpreter tests (audio)
      run: cargo test --lib --features audio
    - name: Run site tests
      run: cargo test -p site
